### ISSUE TITLE
Not working with Odoo v14

### ISSUE THREAD

**Issue by bretif** [Tecnativa/doodba-qa#21]
Hello,
It seems that doodba-qa not working with odoo v14.
After investigation, I see that OCA maintainer Quality Tool (MQT) are no more installed in doodba 14.0.
Is the any reason why v14 is not supported?
I wonder if doodba-qa is still maintened or used with doodba project?
Thanks for your great job on doodba.
Bertrand

**Comment by joao-p-marques** [comment]
Hi @bretif 
As mentioned in https://github.com/Tecnativa/doodba/discussions/367#discussioncomment-266916, `doodba-qa` is becoming less useful for us and will probably be archived at some point. We haven't made any testing for version 14.0 yet and probably won't be able to soon... 
So, as suggested in the comment, maybe the best option is to design your own CI system around your specific needs. https://github.com/Tecnativa/doodba and https://github.com/Tecnativa/doodba-copier-template already pack a lot of useful tools to help with that.
Thanks for reporting the issue!
